name: Carpenter
on:
  push:
    branches:
      - "**"
  release:
    types:
      - published
jobs:
  carpenter:
    uses: jdowni000/arcaflow-plugin-image-builder/.github/workflows/reusable_workflow.yaml@docs
    with:
      image_name: ${{ github.event.repository.name }}
      image_tag: 'latest'
    secrets: inherit
